language: python
python:
  # We don't actually use the Travis Python, but this lets us see 3.7 in most
  # user interfaces for testing and coverage results
  - "3.7"
install:
  - sudo apt-get update && apt-get install -y wget
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda env create -f environment.yml
  - conda activate simple_network_sim

script:
  - pytest --cov=simple_network_sim

after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
